/**
 * The homepage hero frame sequence (spec 0010).
 *
 * Generated by `node scripts/build-hero-frames.mjs` from the raw CAD export in
 * `assets/homepage/hero-src/` (gitignored). Built at module scope so the array
 * identity is stable — `ScrubSequence` keys an effect off it.
 */
export const HERO_FRAME_COUNT = 61;

export const heroFrames: string[] = Array.from(
  { length: HERO_FRAME_COUNT },
  (_, i) => `/homepage/hero/frame-${String(i + 1).padStart(3, "0")}.webp`,
);
